# Generated by Django 4.1 on 2022-08-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tarkibi', models.TextField()),
                ('price', models.IntegerField()),
                ('ctg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg.category')),
            ],
        ),
    ]
