# Generated by Django 4.1 on 2022-08-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('dona', models.IntegerField()),
            ],
        ),
    ]
