# Generated by Django 4.0.6 on 2022-11-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0008_savat_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
