# Generated by Django 4.0.6 on 2022-11-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0009_remove_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ctg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tarkibi',
        ),
        migrations.RemoveField(
            model_name='savat',
            name='dona',
        ),
        migrations.RemoveField(
            model_name='savat',
            name='price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.AddField(
            model_name='product',
            name='bed_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bed_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bed_wide',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='to_bot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wide',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savat',
            name='narxi',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='savat',
            name='summ',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='savat',
            name='product',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='savat',
            name='slug',
            field=models.SlugField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='savat',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True)),
                ('ctg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg.category')),
            ],
        ),
        migrations.CreateModel(
            name='Made_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=128, null=True)),
                ('subctg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='made_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tg.made_in'),
        ),
    ]
