# Generated by Django 4.0.6 on 2022-11-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0010_rename_name_product_material_remove_product_ctg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='content',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='content',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_uz',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.IntegerField(null=True),
        ),
    ]
