# Generated by Django 4.0.6 on 2022-11-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0011_remove_category_content_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='made_in',
            old_name='content',
            new_name='content_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='bed_height',
            new_name='kengligi_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='bed_length',
            new_name='kengligi_uz',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material',
            new_name='material_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='material_uz',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='bed_wide',
            new_name='uzunligi_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='height',
            new_name='uzunligi_uz',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='made_in',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_bed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='to_bot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wide',
        ),
        migrations.AddField(
            model_name='made_in',
            name='content_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
