# Generated by Django 4.0.6 on 2022-11-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0012_rename_content_made_in_content_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
