# Generated by Django 4.0.6 on 2022-11-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0013_rename_user_name_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
