# Generated by Django 4.0.6 on 2022-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0015_user_menu_alter_user_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='menu',
            field=models.IntegerField(null=True),
        ),
    ]
