# Generated by Django 4.0.6 on 2022-11-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0017_alter_user_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='made_in',
            old_name='content_ru',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='kengligi_ru',
            new_name='kengligi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material_ru',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material_uz',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='kengligi_uz',
            new_name='uzunligi',
        ),
        migrations.RemoveField(
            model_name='made_in',
            name='content_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uzunligi_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uzunligi_uz',
        ),
        migrations.AddField(
            model_name='product',
            name='til',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='savat',
            name='til',
            field=models.IntegerField(default=1),
        ),
    ]
