# Generated by Django 4.0.6 on 2022-12-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0018_rename_content_ru_made_in_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lang',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
