# Generated by Django 4.0.6 on 2022-12-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0019_alter_user_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='made_in',
            old_name='content',
            new_name='name_uz',
        ),
        migrations.AddField(
            model_name='made_in',
            name='name_ru',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
    ]
