# Generated by Django 4.0.6 on 2022-12-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0020_rename_content_made_in_name_uz_made_in_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default=11, max_length=128),
            preserve_default=False,
        ),
    ]
