# Generated by Django 4.0.6 on 2022-12-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0021_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
