# Generated by Django 4.0.6 on 2022-12-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0022_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
