# Generated by Django 4.0.6 on 2022-12-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0023_product_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Made_in',
            new_name='Made_in1',
        ),
    ]
