# Generated by Django 4.0.6 on 2022-12-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0024_rename_made_in_made_in1'),
    ]

    operations = [
        migrations.AddField(
            model_name='savat',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
