# Generated by Django 4.0.6 on 2022-12-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0025_savat_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='made_in1',
            old_name='name_uz',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='made_in1',
            name='name_ru',
        ),
    ]
