# Generated by Django 4.0.6 on 2022-12-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0026_rename_name_uz_made_in1_name_remove_made_in1_name_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='made_in1',
            name='til',
            field=models.IntegerField(default=1),
        ),
    ]
