# Generated by Django 4.0.6 on 2023-01-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0028_rename_name_made_in1_name_ru_remove_made_in1_til_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
