# Generated by Django 4.0.6 on 2023-01-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0029_rename_name_product_name_ru_product_name_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='til',
        ),
    ]
