# Generated by Django 4.0.6 on 2023-01-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0032_rename_description_product_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_ru',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_uz',
        ),
    ]
