# Generated by Django 4.0.6 on 2023-01-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0033_rename_price_ru_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='kengligi_ru',
            new_name='kengligi',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='kengligi_uz',
            new_name='uzunligi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uzunligi_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uzunligi_uz',
        ),
    ]
