# Generated by Django 4.0.6 on 2023-01-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0034_rename_kengligi_ru_product_kengligi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='narxi',
        ),
    ]
