# Generated by Django 4.0.6 on 2023-01-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0035_rename_price_product_narxi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kengligi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='narxi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uzunligi',
        ),
    ]
